# -*- coding: utf-8 -*-
"""HW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/177eNR4yKpk2UNABVohvron7ajHNoB06Q
"""

# LEAP YEAR DETECTIVE
year = int(input())

if year % 4 == 0 or year % 100 != 0 and year % 400 == 0:
    print("Leap year")
else:
    print("NOT a Leap year")

import random
# Long arithmetics
number = int(input())

rand_num = ''.join(str(random.randint(0, 9)) for _ in range(100))

print(int(rand_num) // number)

# String matching

text = input()
word = input()

if word in text:
    result1 = text.index(word)
    result2 = result1 + (len(word) - 1)
    print(result1, result2)
else:
    print("No matching")